basePath: /checkout/api
host: localhost:9002
info:
  contact:
    email: ashwinyaal@gmail.com
    name: Ashwin Gopalsamy
  description: This microservice is for checkout service.
  license:
    name: Apache 2.0
  title: Swiggy Qwik - Checkout module
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: This request will return 200 OK if the server is up.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: To check if the service is running or not.
      tags:
      - ""
swagger: "2.0"
