basePath: /checkout/api
host: localhost:9002
info:
  contact:
    email: ashwinyaal@gmail.com
    name: Ashwin Gopalsamy
  description: This microservice is for checkout service.
  license:
    name: Apache 2.0
  title: Swiggy Qwik - Checkout module
  version: "1.0"
paths:
  /:
    get:
      description: used to check whether shipping service is up and running or not
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad Request
          schema:
            type: number
      summary: Health of shipping service
      tags:
      - Health
swagger: "2.0"
