version: "3"
services:
  backend:
    build: .
    ports:
      - "9009:9009"
      - "19091:19091"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
