version: "3"
services:
  rewards:
    build: .
    container_name: rewards
    restart: always
    ports:
      - "9121:9121"
      - "19071:19071"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
