version: "3"
services:
  backend:
    image: mellomaniac/swiggy-qwik:rewards
    ports:
      - "9121:9121"
      - "19071:19071"
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
