basePath: /payment-mode/api
host: localhost:9000
info:
  contact:
    email: aadityakhetan123@gmail.com
    name: Aaditya Khetan
  description: This microservice is for payment_mode service.
  license:
    name: Apache 2.0
  title: Swiggy Qwik - Payment_Mode module
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: This request will return 200 OK if server is up..
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: To check if the service is running or not.
      tags:
      - ""
swagger: "2.0"
