basePath: /products/api
host: localhost:9000
info:
  contact:
    email: akash283y@gmail.com
    name: Akash Yadav
  description: This microservice is for product_admin service.
  license:
    name: Apache 2.0
  title: Swiggy Qwik - Product_Admin module
  version: "1.0"
paths:
  /:
    delete:
      consumes:
      - application/json
      description: Delete Product with given id
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Delete Products
      tags:
      - ""
    get:
      consumes:
      - application/json
      description: Search Product with given query
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Search Products
      tags:
      - ""
    post:
      consumes:
      - application/json
      description: Create a new product object, generate id and save in DB
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: AddProduct
      tags:
      - ""
    put:
      consumes:
      - application/json
      description: Update Product with given id
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Update Products
      tags:
      - ""
swagger: "2.0"
